### ISSUE TITLE
This is a thanks for the job 'non-issue'

### ISSUE THREAD

**Issue by benoitm974** [vulgo/prime-b460i-plus-hackintosh#1]
Just wanted to thank you for the work. I updated my previous build to a B460I-plus and just used you OC config out of the box, working nicely, great job !

just a question I get very verbose output, yet there is "-v" nor the debug setup mention specific verbose level, is this something you've setup somewhere else ?

**Comment by vulgo** [comment]
Maybe `-v` has been set some other way? Check with

```
$ nvram boot-args
```

If `-v` is present, to clear it

```
# nvram boot-args="keepsyms=1"
```

from recovery OS. Alternatively you may reset NVRAM from the OpenCore picker.

Debug is turned off in `config.plist` (target is 0). Should probably enable basic logging for warnings and errors, `HaltLevel` is apparently ignored the way things are i.e. it will boot even with errors.

**Comment by vulgo** [comment]
e11a98a239d9d4a7ae161ce9a937fab33ac8e52d

**Comment by benoitm974** [comment]
indeed it was a left over in nvram, sorry to have bothered with this ! Thanks again for your work.
