### ISSUE TITLE
Ventura

### ISSUE THREAD

**Issue by lazosweb** [vulgo/prime-b460i-plus-hackintosh#17]
Hi @vulgo ,

Shall I update to Ventura? I will backup everything if things go sideways, will find a way to restore, maybe. :)

**Comment by vulgo** [comment]
Hi @lazosweb i think it is ok, "next" branch should be fine afaik the kaby
lake macs use some similar hardware and device ids to our b460i. I've been
distracted, almost updated last week, next week will upgrade and if
everything goes well merge 0.8.5 / macOS 13

**Comment by lazosweb** [comment]
@vulgo all went well... I do not see any issues.

**Comment by vulgo** [comment]
Thanks @lazosweb let me know if anything comes up, if i don't hear from you
i'll merge next on Saturday. Thanks.
