### ISSUE TITLE
New 0.8.5 hang

### ISSUE THREAD

**Issue by benoitm974** [vulgo/prime-b460i-plus-hackintosh#18]
I there, first want to thanks again for your work on prime B460i, greatly appreciated!

I wanted to test the new mac os 13 and decided to create a new USB key using your latest 0.8.5 release, yet even after nvram flash, adjusting the GPU and generic/Serial number section in config, tried both the provided  USB kext or a newly generated kext from my working Monterey setup: I can't make neither my Monterey boot nor the Ventura install to start. 

Before I download debug version and start a new setup wanted to know if you had anything special done, it seems you're using the AMD video card, have you tried or any advice on the usage of iGPU ?

Thanks for any tips to debug.

**Comment by lazosweb** [comment]
Hi @benoitm974,

I will only comment on the iGPU part. If you look at the opened issues you will find a long discussion with @vulgo.
I have a 10th gen 10600 (non K) version.

The only issue I had is using Dual Monitors and specifically the HDMI port... In order to make it work you have to either turn the monitor on and off or if you read the discussion there is a specific flag that solved it for me.

If you are not using dual monitors and you will use the DP port you should be ok.

**Comment by benoitm974** [comment]
Thanks for you reply I have 10th i9 10900 not K version either. How would you caracterise the screen issue, since on my side I see the Firevault screen I can enter the password I see the loading screen but no progression bar then it hang, or booting ventura, I can see the Apple logo but not progression bar then is hang. I don't think this is screen issue?

**Comment by vulgo** [comment]
Hello @benoitm974, sorry but you'll need to boot in verbose mode by adding -v to boot arguments and download a debug version following the instructions [here](
https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/debug.html#file-swaps)

I know it's a pain but it might save us time in the long run. Where are we in the boot stage? I can't tell.

> have you tried or any advice on the usage of iGPU

Yes, try not to use it, the iGPU issues are very unique to Apple's Skylake-ported drivers and modeset commands, @lazosweb is willing to tolerate them!

**Comment by vulgo** [comment]
@benoitm974 be careful generating many serial numbers, not that it's booting right now

**Comment by lazosweb** [comment]
@benoitm974 The screen issue you will see it when you OS is loaded and you are prompt with the login screen.
The screen will have artifacts or something.

**Comment by benoitm974** [comment]
@vulgo Sorry but i'm not sure to understand " be careful generating many serial numbers, not that it's booting right now" ?
Also please don't be sorry for the debugging/pain: you're already saving me so many hours with this repo! It's a pleasure to go debug then :)

**Comment by vulgo** [comment]
@benoitm974 re: serial numbers stick with the same ones, re: debugging don't speak too soon... hopefully it is something simple

**Comment by benoitm974** [comment]
As I enabled debug one thing I note (but it didn't solve my issue) the filename of SSDT-AWAC-DISABLE.aml is named SSDT-AWAC-HPET-DISABLE.aml in the config.plist provided on the latest git version.

![Screenshot 2022-11-02 at 13 22 33](https://user-images.githubusercontent.com/1139277/199490067-6346a6ff-c971-4634-a3fe-df26c35bfe14.png)

**Comment by vulgo** [comment]
> As I enabled debug one thing I note (but it didn't solve my issue) the filename of SSDT-AWAC-DISABLE.aml is named SSDT-AWAC-HPET-DISABLE.aml in the config.plist provided on the latest git version.

Yes, it has been that way for a few months. Double check that file exists in the ACPI folder.

Edit: I just noticed your screenshot, it doesn't - either rename it in `config.plist` or copy the HPET version from the repo. Be careful mixing and matching files provided here with your own files

**Comment by vulgo** [comment]
Also turn off file vault and other security measures for testing purposes

**Comment by vulgo** [comment]
@benoitm974 have you had any luck with starting the OS?

**Comment by benoitm974** [comment]
No luck I’ve tried with the hpet aml or without hpet all.

tried with my aml from working 0.8.1 binary from 0.8.5 no luck

enabled full debug binary and config plist the log stop at eb log exit bs start i tried the doc suggestion from here https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/extended/kernel-issues.html#stuck-on-eb-log-exitbs-start

but still stuck trying to boot the installer

**Comment by vulgo** [comment]
- Copy the entire EFI folder from the repo to a newly formatted USB drive
- Copy the serials from your previous install to `config.plist`
- If you are using the iGPU copy the iGPU device properties from the repo readme to `config.plist`
- Replace `USBPorts.kext` with the one from your previous install
- Reset NVRAM
- Try and boot the installer

**Comment by benoitm974** [comment]
I tried just that even before posting here … I even did it with a Monterey new usb disk and a 0.8.1 it works doing the same what you describe with the 0.8.5 doesn’t work …

**Comment by vulgo** [comment]
Post the boot.efi messages

**Comment by vulgo** [comment]
and EFI folder

**Comment by vulgo** [comment]
Can you boot Monterey with 0.8.5? You need to show the log and upload the EFI config you are using.

**Comment by ruibty** [comment]
i just replace the 'ACPI' folder with 0.8.1 and it works.
https://github.com/ruibty/prime-b460i-plus-hackintosh

**Comment by ruibty** [comment]
I just replace the 'ACPI' folder with 0.8.1 and it works.
https://github.com/ruibty/prime-b460i-plus-hackintosh

**Comment by vulgo** [comment]
@rubity thank you, one of the AML files was missing, @benoitm974 had in fact pointed this out but it didn't solve his problem. I think the ACPI folder is now fixed as of [db9de0c](https://github.com/vulgo/prime-b460i-plus-hackintosh/commit/db9de0c0def9ae3f83527d001e83d8f9f61205aa)

**Comment by ruibty** [comment]
@vulgo It's my pleasure, you're already do what an important work for me!

**Comment by benoitm974** [comment]
I just can't explain it, the version from Ruibty works out of the box i can install macOS 13. I might have miss a copy or trying different version, but thanks both @vulgo & @ruibty.
Benoit

**Comment by vulgo** [comment]
@benoitm974 I can't explain it either without your debug logs and the EFI folder you are using

**Comment by vulgo** [comment]
Everyone use @ruibty's https://github.com/ruibty/prime-b460i-plus-hackintosh

**Comment by benoitm974** [comment]
Apparently the only differences are thoses in the attached file.

I think the interesting part is the "Binary files ruibty/OpenCore-0.8.5/EFI/OC/ACPI/SSDT-AWAC-HPET-DISABLE.aml and vulgo/OpenCore-0.8.5/EFI/OC/ACPI/SSDT-AWAC-HPET-DISABLE.aml differ" 

Possibly @vulgo your aml version last commit was with another or different version ?

The other difference are about adding some efi Drivers for nvram & SipEntry ... not relevant here..
[diff_85.txt](https://github.com/vulgo/prime-b460i-plus-hackintosh/files/9946772/diff_85.txt)

**Comment by benoitm974** [comment]
Can this be the only change that would cause an issue ?
below decompiled different AML from both repository.
![Screenshot 2022-11-06 at 21 31 22](https://user-images.githubusercontent.com/1139277/200193712-f9daa219-61f4-4f98-8e17-c6b9e16d5868.png)

**Comment by vulgo** [comment]
@benoitm974 yes i think it's the forward reference and !CondRefOf (_SB._INI) check that is killing it. I'll update the repo. If @ruibty's is working just stay on that. Thanks!
