### ISSUE TITLE
Info.plist is missing

### ISSUE THREAD

**Issue by ghost** [vulgo/prime-b460i-plus-hackintosh#20]
Tried this EFI for exactly the same motherboard but get the following error during boot: 
`Plist Kexts\VirtualSMC.kext\Contents\Plugins\SMProcessor.kext\Contents\Info.plist is missing for injected kext VirtualSMC.kext\Contents\Plugins\SMProcessor.kext (VirtualSMC.kext CPU Monitor Plugin)`
NVRAM was reset.

**Comment by vulgo** [comment]
Hi. Move SMCProcessor.kext & SMCSuperIO.kext to VirtualSMC.kext/Contents/Plugins

**Comment by ghost** [comment]
What's the point of having them inside VirtualSMC kext anyway? Why not keep every kext in `Kext` folder, like it's usually done?

**Comment by vulgo** [comment]
Apple's kexts use the PlugIns directory extensively. You can edit the
config.plist or move the files
