### ISSUE TITLE
Ordered the same board

### ISSUE THREAD

**Issue by lazosweb** [vulgo/prime-b460i-plus-hackintosh#4]
Hi,

I ordered yesterday the same board after looking at your repository. How are u getting along with it? Is it ok?

After reading the open core documentation what I understood is that the only issue with this board are the messy USBs, did you face any other issues?

Thanks.

**Comment by vulgo** [comment]
Updating the firmware was essential. Version 1301 is now available from [asus.com](https://www.asus.com/uk/Motherboards-Components/Motherboards/PRIME/PRIME-B460I-PLUS/HelpDesk_BIOS/).

I'm using

- a compatible GPU, there's an incomplete list [on this page](https://support.apple.com/en-gb/HT208544)
- BCM94360NG wireless card
- NVMe storage with [NVMeFix.kext](https://github.com/acidanthera/NVMeFix/releases)

macOS works very well.

**Comment by lazosweb** [comment]
Thanks for letting me know about the firmware. I will use the i5 10500 iGPU and no wireless. I will use just the Realtek Ethernet. The wireless card is the M.2 one correct? For NVME will use the WD Black 500GB SN750. I read in Open Core documentation that Apple does not like the Samsung Phoenix controller...
Trying to build a Mac Mini look alike with a nano PSU.
Again, thanks for replying.

**Comment by vulgo** [comment]
M.2 wireless. Realtek ethernet works well with Mieze's kext.

A possible issue with the iGPU is there is no DRM content support in Apple apps. Also i haven't used iGPU video output, it might require [further steps](https://dortania.github.io/OpenCore-Post-Install/gpu-patching/intel-patching/) to get it working. If that is the case I will update the repo.

That CPU has its default PL2 at 138W, or 11.5 amps from the 12V rail just for the CPU.  HDPLEX 200W DC-ATX can supply that, regulated 12V from 19V input.

**Comment by lazosweb** [comment]
If those DRM contents are Apple TV, Netflix and Prime TV etc... these stuff I do not really care (half of them are not even available in my country :D). I will use it mainly for developing purposes than entertainment...

Regarding the iGPU indeed further steps are required. From what I understood (from opencore documentation) those frame buffers will make it work and be able to use dual output for dual monitors.

Thanks for the info about the CPU can you send me a link where did you find this?

Edit: Found it here https://www.tomshardware.com/news/intel-pl1-pl2-tau-10th-gen-comet-lake-processors

**Comment by vulgo** [comment]
If and when your HDMI and DisplayPort outputs are working please comment or share the configuration, i will update the repo. Thanks.

**Comment by lazosweb** [comment]
Hi @vulgo. I built the PC yesterday, after mentioning the 10500 PL2, we ended up buying the 10600 instead with a better PSU (250W), funny story bought from Amazon DE, it came last week but CPU was missing. Fully refunded and we bought a similar CPU from Amazon UK...
Anyway, my setup as I mentioned above is very simple, Core i5 10600, WD Black 500GB, I flashed the BIOS to latest, I do not have PCI-E Wifi BT...

I followed the Open Core guide and it was kernel panicking after a few changes here and there it did work, started installing and now every time it resets I am getting the "System POSTed in safe mode". Did you have something similar?

The ACPI AML files can I download and use yours are they related to the hardware that you and I have or not? I know the KEXTs, the drivers, the serial numbers etc... must be different but I am wondering what I can take from your end to make my life easier...

Edit: I think enabling DisableRtcChecksum fixed it...

Thanks.

**Comment by vulgo** [comment]
The files in the repo are supposed to be as generic as possible. The default ```ig-platform-id``` is for discrete graphics.

If you remove Dortania ACPI, you can use the ACPI ```.AML``` files from the repo as they are specific only to b460i-plus, but also copy the ```ACPI``` section of the ```config.plist``` and the ```XHC: inject supported device ID``` device property. Then ```USBPortInjector.kext``` can be edited and added, or you can instead add similar e.g. Hackintool generated files or you can not have a ```USB*.kext``` at all and the port map can be done in the SSDT, refer to the readmes. Don't enable the port limit quirk. Non working USB breaks more than just USB.

In ```config.plist``` ```Kernel```->```Quirks``` try enabling the ```DisableRtcChecksum``` quirk, that may solve your post in safe mode error problem.

If you are not already, when making changes from the OC ```sample.plist``` (any source), do refer to the OC ```Docs/Configuration.pdf``` document.

**Comment by lazosweb** [comment]
Yes, the DisableRtcChecksum fixed it... you did not have similar issue?

Thank you. I will do what you said above.

**Comment by vulgo** [comment]
Yes, it's in the config.plist :smile:

**Comment by lazosweb** [comment]
@vulgo I do not know what I am doing wrong... I tried so many combos, I used hackintool and everything in order to patch the iGPU and it does not work. When the PC reboots the HDMI cable (if the DP cable is also connected) does not work. Either a blackscreen for HDMI or the picture is distorted and I have to remove the DP cable. I tried different cables etc... nothing works. I know you have a dGPU but do you have any tips for me? Is driving me mad... :(

Edit1: Read on a post that adding the boot-arg igfxonln=1 sorts out the sleeping issue with the monitors.
Edit2: Well, I do not know if this is an issue related to those patches or not but if on every reboot if I turn the DP monitor off and on (boots quickly) the problem is resolved...

**Comment by vulgo** [comment]
Good work @lazosweb. I will also investigate this and let you know what I find.

**Comment by lazosweb** [comment]
Other than that I do not see anything else. The PC restarts and shuts down properly. It sleeps and wakes up without any issue. The Hardware Acceleration of the iGPU works fine, App Store works. Messages, FaceTime, or whatever other Apple/iPhone related app I do not  need them...

Thanks for all your support and comments.

**Comment by vulgo** [comment]
@lazosweb please try these connector edits from defaults in Hackintool...

| Intel Generation | Platform ID |
|:-----------------|:------------|
| Coffee Lake      | 0x3E9B007   |

Connectors:
```Index 2``` -> Type -> ```HDMI```
```Index 3``` -> Type -> ```Dummy```
```Index 3``` -> Flags -> ```0x00000020``` (same as ```Index -1```)

| Index   | Bus ID   | Pipe   | Type   | Flags       |
|:--------|:---------|:-------|:-------|:------------|
| 1       | 0x05     | 9      | DP     | 0x000003C7  |
| 2       | 0x04     | 10     | HDMI   | 0x000003C7  |
| 3       | 0x06     | 8      | Dummy  | 0x00000020  |
| -1       | 0x00     | 0      | Dummy  | 0x00000020  |

![hackintool-patch-general](https://user-images.githubusercontent.com/74738713/132984097-b99ea27b-a50b-451c-9ff6-d59d907a4794.png)

Patch (Advanced):
Nothing selected (unchecked all)

Result...

```xml
<key>PciRoot(0x0)/Pci(0x2,0x0)</key>
<dict>
	<key>AAPL,ig-platform-id</key>
	<data>BwCbPg==</data>
	<key>framebuffer-con1-alldata</key>
	<data>AgQKAAAIAADHAwAAAwYIAAEAAAAgAAAA</data>
	<key>framebuffer-con1-enable</key>
	<data>AQAAAA==</data>
	<key>framebuffer-patch-enable</key>
	<data>AQAAAA==</data>
</dict>
```

**Comment by lazosweb** [comment]
Doing it now...

**Comment by lazosweb** [comment]
Same no change...

**Comment by lazosweb** [comment]
I made a video so you can see what is going on...
Left Monitor HDMI (Resolution 1440p)
Right Monitor DP (Resolution 1440p)
https://youtu.be/ObnehzI1ZoQ

Thanks

**Comment by lazosweb** [comment]
And after the reboot if I do not turn off the DP monitor off, after a minute the HDMI screen looks like that.

I even swapped the cables and same thing happens...

This happens after a shutdown and a reboot. If I turn off the DP monitor then even if the monitors go to sleep or the PC hibernates it wont happen again. Only after a reboot and a shutdown. 

![20210912_135927](https://user-images.githubusercontent.com/19972355/132985044-f5f0e72c-93f4-43c8-9ef5-cfc6b7bbe39c.jpg)

**Comment by vulgo** [comment]
Yes i'm seeing the same problem when booting with 2 monitors.

Similar sounding and also using ASUS firmware...
[https://www.reddit.com/r/hackintosh/comments/j0ags8/graphical_artifacts_when_booting_with_dual/](https://www.reddit.com/r/hackintosh/comments/j0ags8/graphical_artifacts_when_booting_with_dual/)
[https://www.reddit.com/r/hackintosh/comments/hulehu/dual_display_with_igpu_hd630_black_screen_and/](https://www.reddit.com/r/hackintosh/comments/hulehu/dual_display_with_igpu_hd630_black_screen_and/)
[https://www.reddit.com/r/hackintosh/comments/hx3fsd/black_bars_through_the_screen_when_using/](https://www.reddit.com/r/hackintosh/comments/hx3fsd/black_bars_through_the_screen_when_using/)

**Comment by lazosweb** [comment]
Hmmmmm you are right this is happening only on ASUS boards :(. No one found a solution for it...

Anyway, like I said, I do not really mind turning on and off the second monitor.

Maybe you should write it in your readme file. If you want to use this board buy a dedicate card if you find a cheap one... :D

**Comment by vulgo** [comment]
There are no cheap graphics cards, selling your second monitor will raise the cash, but then the iGPU will function correctly.

Open issue for the 2-monitor boot problem: #5

**Comment by lazosweb** [comment]
Unfortunately due to the nature of my job (Web Programmer) not having a second monitor is a nightmare. I am not yet mentally prepared to have a 4k monitor. :)
